# Form implementation generated from reading ui file 'D:\FINALPROJECT\models\user\tabAccount\feature_change_password\ChangePasswordMainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 643)
        MainWindow.setStyleSheet("QMainWindow{\n"
"    background-color: white;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_2 = QtWidgets.QWidget(parent=self.widget)
        self.widget_2.setStyleSheet("background-color:rgb(255, 251, 241)")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(parent=self.widget_2)
        self.label.setStyleSheet("color: #c40c0c; font-size: 20px;font-weight: bold; font-family: \"UTM Avo\";")
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.pushButton = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton.setStyleSheet("border: 2px solid ; border-radius: 8px; padding: 10px 15px; font-weight: bold; font-family: \"UTM Avo\"; font-size: 17px;background-color:rgb(255, 251, 241);\n"
"border-color: rgb(255, 251, 241);")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\FINALPROJECT\\models\\user\\tabAccount\\feature_change_password\\../../../../images/icon_x.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.horizontalLayout_3.setStretch(0, 5)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.label_2 = QtWidgets.QLabel(parent=self.widget_2)
        font = QtGui.QFont()
        font.setFamily("UTM Avo")
        font.setPointSize(-1)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel{\n"
"    font-family: UTM Avo;\n"
"    font-size:16px;\n"
"}\n"
"")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.lineEditOldPass = QtWidgets.QLineEdit(parent=self.widget_2)
        font = QtGui.QFont()
        font.setFamily("UTM Avo")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditOldPass.setFont(font)
        self.lineEditOldPass.setStyleSheet("background-color: #ffffff; border: 2px solid #ffc100; border-radius: 8px; padding: 10px 15px; font-weight: bold; font-family: \"UTM Avo\"; font-size: 17px;\n"
"color: rgb(0, 0, 0);")
        self.lineEditOldPass.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditOldPass.setObjectName("lineEditOldPass")
        self.verticalLayout_2.addWidget(self.lineEditOldPass)
        self.label_3 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_3.setStyleSheet("QLabel{\n"
"    font-family: UTM Avo;\n"
"    font-size:16px;\n"
"}\n"
"")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.lineEditNewPass = QtWidgets.QLineEdit(parent=self.widget_2)
        self.lineEditNewPass.setStyleSheet("background-color: #ffffff; border: 2px solid #ffc100; border-radius: 8px; padding: 10px 15px; font-weight: bold; font-family: \"UTM Avo\"; font-size: 17px;\n"
"color: rgb(0, 0, 0);")
        self.lineEditNewPass.setObjectName("lineEditNewPass")
        self.verticalLayout_2.addWidget(self.lineEditNewPass)
        self.label_4 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_4.setStyleSheet("QLabel{\n"
"    font-family: UTM Avo;\n"
"    font-size:16px;\n"
"}\n"
"")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.lineEditNewPass_2 = QtWidgets.QLineEdit(parent=self.widget_2)
        self.lineEditNewPass_2.setStyleSheet("background-color: #ffffff; border: 2px solid #ffc100; border-radius: 8px; padding: 10px 15px; font-weight: bold; font-family: \"UTM Avo\"; font-size: 17px;\n"
"color: rgb(0, 0, 0);")
        self.lineEditNewPass_2.setObjectName("lineEditNewPass_2")
        self.verticalLayout_2.addWidget(self.lineEditNewPass_2)
        self.label_5 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnCancel = QtWidgets.QPushButton(parent=self.widget_2)
        self.btnCancel.setStyleSheet("border: 2px solid ; border-radius: 8px; padding: 10px 15px; font-weight: bold; font-family: \"UTM Avo\"; font-size: 17px;\n"
"border-color: rgb(163, 158, 166);\n"
"color: rgb(0, 0, 0);")
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout.addWidget(self.btnCancel)
        self.btnConfirm = QtWidgets.QPushButton(parent=self.widget_2)
        self.btnConfirm.setStyleSheet("border: 2px solid ; border-radius: 8px; padding: 10px 15px; font-weight: bold; font-family: \"UTM Avo\"; font-size: 17px;\n"
"border-color: rgb(255, 101, 0);\n"
"background-color: rgb(255, 101, 0);\n"
"color: rgb(255, 255, 255);")
        self.btnConfirm.setObjectName("btnConfirm")
        self.horizontalLayout.addWidget(self.btnConfirm)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.setStretch(0, 9)
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.verticalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Đổi mật khẩu"))
        self.label_2.setText(_translate("MainWindow", "Mật khẩu cũ"))
        self.label_3.setText(_translate("MainWindow", "Mật khẩu mới"))
        self.label_4.setText(_translate("MainWindow", "Xác nhận mật khẩu"))
        self.btnCancel.setText(_translate("MainWindow", "Huỷ"))
        self.btnConfirm.setText(_translate("MainWindow", "Xác nhận"))
