# Form implementation generated from reading ui file 'D:\KTLT\FINAL_EXAM\Home\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.BookingPage = QtWidgets.QWidget()
        self.BookingPage.setObjectName("BookingPage")
        self.label = QtWidgets.QLabel(parent=self.BookingPage)
        self.label.setGeometry(QtCore.QRect(130, 30, 521, 441))
        self.label.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\\KTLT\\FINAL_EXAM\\Home\\../USER/Login/images/logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.BookingPage)
        self.CheckDatePage = QtWidgets.QWidget()
        self.CheckDatePage.setObjectName("CheckDatePage")
        self.stackedWidget.addWidget(self.CheckDatePage)
        self.verticalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
