# Form implementation generated from reading ui file 'D:\FINALPROJECT\models\login\ui\forgotPasswordMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 700)
        MainWindow.setStyleSheet("background-color: #FDF0E0;")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.forgotCard = QtWidgets.QFrame(parent=self.centralwidget)
        self.forgotCard.setMinimumSize(QtCore.QSize(400, 450))
        self.forgotCard.setMaximumSize(QtCore.QSize(400, 450))
        self.forgotCard.setStyleSheet("background-color: white; border-radius: 30px;")
        self.forgotCard.setObjectName("forgotCard")
        self.logoLabel = QtWidgets.QLabel(parent=self.forgotCard)
        self.logoLabel.setGeometry(QtCore.QRect(150, 30, 100, 100))
        self.logoLabel.setPixmap(QtGui.QPixmap("D:\\FINALPROJECT\\models\\login\\ui\\../images/logo.png"))
        self.logoLabel.setScaledContents(True)
        self.logoLabel.setObjectName("logoLabel")
        self.titleLabel = QtWidgets.QLabel(parent=self.forgotCard)
        self.titleLabel.setGeometry(QtCore.QRect(0, 140, 400, 40))
        self.titleLabel.setStyleSheet("color: rgb(165, 54, 27);")
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.labelEmail = QtWidgets.QLabel(parent=self.forgotCard)
        self.labelEmail.setGeometry(QtCore.QRect(40, 200, 200, 20))
        self.labelEmail.setStyleSheet("color: #666; font-size: 13px;")
        self.labelEmail.setObjectName("labelEmail")
        self.lineEditEmail = QtWidgets.QLineEdit(parent=self.forgotCard)
        self.lineEditEmail.setGeometry(QtCore.QRect(40, 225, 320, 45))
        self.lineEditEmail.setStyleSheet("border: none; background-color: #F0F2F5; border-radius: 12px; padding-left: 15px;")
        self.lineEditEmail.setObjectName("lineEditEmail")
        self.pushButtonReset = QtWidgets.QPushButton(parent=self.forgotCard)
        self.pushButtonReset.setGeometry(QtCore.QRect(40, 300, 320, 50))
        self.pushButtonReset.setStyleSheet("background-color: #FF6600; color: white; font-weight: bold; font-size: 14pt; border-radius: 15px;")
        self.pushButtonReset.setObjectName("pushButtonReset")
        self.horizontalLayout.addWidget(self.forgotCard)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "New Year Photo - Quên mật khẩu"))
        self.titleLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt; font-weight:600;\">Quên mật khẩu</span></p></body></html>"))
        self.labelEmail.setText(_translate("MainWindow", "Email"))
        self.lineEditEmail.setPlaceholderText(_translate("MainWindow", "Nhập email đã đăng ký"))
        self.pushButtonReset.setText(_translate("MainWindow", "Đặt lại mật khẩu"))
