# Form implementation generated from reading ui_Account file 'D:\NAM_1\Kythuatlaptrinh\K25411_KTLT\dang_nhap\ui_Account\resetPasswordMainWindow.ui_Account'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 750)
        MainWindow.setStyleSheet("background-color: #FDF0E0;")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.resetCard = QtWidgets.QFrame(parent=self.centralwidget)
        self.resetCard.setMinimumSize(QtCore.QSize(400, 500))
        self.resetCard.setMaximumSize(QtCore.QSize(400, 500))
        self.resetCard.setStyleSheet("background-color: white; border-radius: 30px;")
        self.resetCard.setObjectName("resetCard")
        self.logoLabel = QtWidgets.QLabel(parent=self.resetCard)
        self.logoLabel.setGeometry(QtCore.QRect(150, 40, 100, 100))
        self.logoLabel.setPixmap(QtGui.QPixmap("D:\\NAM_1\\Kythuatlaptrinh\\K25411_KTLT\\dang_nhap\\ui_Account\\../images/logo.png"))
        self.logoLabel.setScaledContents(True)
        self.logoLabel.setObjectName("logoLabel")
        self.titleLabel = QtWidgets.QLabel(parent=self.resetCard)
        self.titleLabel.setGeometry(QtCore.QRect(0, 160, 400, 40))
        self.titleLabel.setStyleSheet("font: 700 18pt \'Segoe UI\'; color: #FF6600;")
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.labelNewPass = QtWidgets.QLabel(parent=self.resetCard)
        self.labelNewPass.setGeometry(QtCore.QRect(40, 220, 200, 20))
        self.labelNewPass.setStyleSheet("color: #333; font-size: 13px;")
        self.labelNewPass.setObjectName("labelNewPass")
        self.lineEditNewPass = QtWidgets.QLineEdit(parent=self.resetCard)
        self.lineEditNewPass.setGeometry(QtCore.QRect(40, 245, 320, 45))
        self.lineEditNewPass.setStyleSheet("border: none; background-color: #F0F2F5; border-radius: 12px; padding-left: 15px;")
        self.lineEditNewPass.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditNewPass.setObjectName("lineEditNewPass")
        self.labelConfirmPass = QtWidgets.QLabel(parent=self.resetCard)
        self.labelConfirmPass.setGeometry(QtCore.QRect(40, 300, 200, 20))
        self.labelConfirmPass.setStyleSheet("color: #333; font-size: 13px;")
        self.labelConfirmPass.setObjectName("labelConfirmPass")
        self.lineEditConfirmNewPass = QtWidgets.QLineEdit(parent=self.resetCard)
        self.lineEditConfirmNewPass.setGeometry(QtCore.QRect(40, 325, 320, 45))
        self.lineEditConfirmNewPass.setStyleSheet("border: none; background-color: #F0F2F5; border-radius: 12px; padding-left: 15px;")
        self.lineEditConfirmNewPass.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditConfirmNewPass.setObjectName("lineEditConfirmNewPass")
        self.pushButtonResetAction = QtWidgets.QPushButton(parent=self.resetCard)
        self.pushButtonResetAction.setGeometry(QtCore.QRect(40, 400, 320, 50))
        self.pushButtonResetAction.setStyleSheet("background-color: #FF6600; color: white; font-weight: bold; font-size: 14pt; border-radius: 15px;")
        self.pushButtonResetAction.setObjectName("pushButtonResetAction")
        self.horizontalLayout.addWidget(self.resetCard)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "New Year Photo - Đặt lại mật khẩu"))
        self.titleLabel.setText(_translate("MainWindow", "Đặt lại mật khẩu"))
        self.labelNewPass.setText(_translate("MainWindow", "Mật khẩu mới"))
        self.lineEditNewPass.setPlaceholderText(_translate("MainWindow", "Nhập mật khẩu mới"))
        self.labelConfirmPass.setText(_translate("MainWindow", "Xác nhận mật khẩu mới"))
        self.lineEditConfirmNewPass.setPlaceholderText(_translate("MainWindow", "Nhập lại mật khẩu mới"))
        self.pushButtonResetAction.setText(_translate("MainWindow", "Đặt lại mật khẩu"))
