# Form implementation generated from reading ui file 'D:\NAM_1\Kythuatlaptrinh\K25411_KTLT\dang_nhap\ui\updateMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AdminSettingsWindow(object):
    def setupUi(self, AdminSettingsWindow):
        AdminSettingsWindow.setObjectName("AdminSettingsWindow")
        AdminSettingsWindow.resize(1000, 850)
        AdminSettingsWindow.setStyleSheet("background-color: #FDF0E0;")
        self.centralwidget = QtWidgets.QWidget(parent=AdminSettingsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainCard = QtWidgets.QFrame(parent=self.centralwidget)
        self.mainCard.setStyleSheet("background-color: white; border-radius: 30px;")
        self.mainCard.setObjectName("mainCard")
        self.cardLayout = QtWidgets.QVBoxLayout(self.mainCard)
        self.cardLayout.setContentsMargins(50, 40, 50, 40)
        self.cardLayout.setSpacing(20)
        self.cardLayout.setObjectName("cardLayout")
        self.logoContainer = QtWidgets.QHBoxLayout()
        self.logoContainer.setObjectName("logoContainer")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.logoContainer.addItem(spacerItem)
        self.logoLabel = QtWidgets.QLabel(parent=self.mainCard)
        self.logoLabel.setMinimumSize(QtCore.QSize(150, 150))
        self.logoLabel.setMaximumSize(QtCore.QSize(150, 150))
        self.logoLabel.setPixmap(QtGui.QPixmap("D:\\NAM_1\\Kythuatlaptrinh\\K25411_KTLT\\dang_nhap\\ui\\../images/logo.png"))
        self.logoLabel.setScaledContents(True)
        self.logoLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.logoLabel.setObjectName("logoLabel")
        self.logoContainer.addWidget(self.logoLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.logoContainer.addItem(spacerItem1)
        self.cardLayout.addLayout(self.logoContainer)
        self.titleLabel = QtWidgets.QLabel(parent=self.mainCard)
        self.titleLabel.setStyleSheet("color: #A5361B; font: 75 24pt \"Segoe UI Variable Display\"; font-weight: bold;")
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.cardLayout.addWidget(self.titleLabel)
        self.conceptGroup = QtWidgets.QGroupBox(parent=self.mainCard)
        self.conceptGroup.setStyleSheet("\n"
"            QGroupBox {\n"
"                font-weight: bold;\n"
"                color: #A5361B;\n"
"                border: 2px solid #FF9966;\n"
"                border-radius: 20px;\n"
"                margin-top: 20px;\n"
"                padding-top: 25px;\n"
"                background-color: #FFF9F5;\n"
"            }\n"
"            QGroupBox::title {\n"
"                subcontrol-origin: margin;\n"
"                left: 20px;\n"
"                padding: 0 5px;\n"
"            }\n"
"          ")
        self.conceptGroup.setObjectName("conceptGroup")
        self.gridLayout = QtWidgets.QGridLayout(self.conceptGroup)
        self.gridLayout.setVerticalSpacing(15)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl1 = QtWidgets.QLabel(parent=self.conceptGroup)
        self.lbl1.setObjectName("lbl1")
        self.gridLayout.addWidget(self.lbl1, 0, 0, 1, 1)
        self.lineEditConceptName = QtWidgets.QLineEdit(parent=self.conceptGroup)
        self.lineEditConceptName.setStyleSheet("border: 1px solid #FF9966; border-radius: 10px; padding: 8px; background: white;")
        self.lineEditConceptName.setObjectName("lineEditConceptName")
        self.gridLayout.addWidget(self.lineEditConceptName, 0, 1, 1, 1)
        self.lbl2 = QtWidgets.QLabel(parent=self.conceptGroup)
        self.lbl2.setObjectName("lbl2")
        self.gridLayout.addWidget(self.lbl2, 1, 0, 1, 1)
        self.lineEditPrice = QtWidgets.QLineEdit(parent=self.conceptGroup)
        self.lineEditPrice.setStyleSheet("border: 1px solid #FF9966; border-radius: 10px; padding: 8px; background: white;")
        self.lineEditPrice.setObjectName("lineEditPrice")
        self.gridLayout.addWidget(self.lineEditPrice, 1, 1, 1, 1)
        self.cardLayout.addWidget(self.conceptGroup)
        self.lblPolicy = QtWidgets.QLabel(parent=self.mainCard)
        self.lblPolicy.setStyleSheet("font-weight: bold; color: #555;")
        self.lblPolicy.setObjectName("lblPolicy")
        self.cardLayout.addWidget(self.lblPolicy)
        self.textEditPolicy = QtWidgets.QTextEdit(parent=self.mainCard)
        self.textEditPolicy.setStyleSheet("border: 2px solid #EEE; border-radius: 15px; padding: 15px; background-color: #FAFAFA; color: #333;")
        self.textEditPolicy.setObjectName("textEditPolicy")
        self.cardLayout.addWidget(self.textEditPolicy)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.buttonLayout.addItem(spacerItem2)
        self.pushButtonSave = QtWidgets.QPushButton(parent=self.mainCard)
        self.pushButtonSave.setMinimumSize(QtCore.QSize(320, 60))
        self.pushButtonSave.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButtonSave.setStyleSheet("\n"
"              QPushButton {\n"
"                  background-color: #FF6600;\n"
"                  color: white;\n"
"                  font-weight: bold;\n"
"                  font-size: 14pt;\n"
"                  border-radius: 20px;\n"
"                  border: none;\n"
"              }\n"
"              QPushButton:hover {\n"
"                  background-color: #FF8533;\n"
"                  margin-top: -2px;\n"
"              }\n"
"              QPushButton:pressed {\n"
"                  background-color: #E65C00;\n"
"              }\n"
"            ")
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.buttonLayout.addWidget(self.pushButtonSave)
        self.cardLayout.addLayout(self.buttonLayout)
        self.verticalLayout.addWidget(self.mainCard)
        AdminSettingsWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(AdminSettingsWindow)
        QtCore.QMetaObject.connectSlotsByName(AdminSettingsWindow)

    def retranslateUi(self, AdminSettingsWindow):
        _translate = QtCore.QCoreApplication.translate
        AdminSettingsWindow.setWindowTitle(_translate("AdminSettingsWindow", "New Year Photo - Quản lý Hệ thống"))
        self.titleLabel.setText(_translate("AdminSettingsWindow", "ĐIỀU CHỈNH CHÍNH SÁCH & GIÁ CẢ CONCEPT"))
        self.conceptGroup.setTitle(_translate("AdminSettingsWindow", " 📸 CẬP NHẬT CONCEPT & GIÁ"))
        self.lbl1.setText(_translate("AdminSettingsWindow", "📌 Tên Concept:"))
        self.lineEditConceptName.setPlaceholderText(_translate("AdminSettingsWindow", "Ví dụ: Concept Tết Cổ Truyền..."))
        self.lbl2.setText(_translate("AdminSettingsWindow", "💰 Giá dịch vụ:"))
        self.lineEditPrice.setPlaceholderText(_translate("AdminSettingsWindow", "Nhập số tiền (VNĐ)..."))
        self.lblPolicy.setText(_translate("AdminSettingsWindow", "📜 Chính sách & Điều khoản mới:"))
        self.pushButtonSave.setText(_translate("AdminSettingsWindow", "🚀 LƯU VÀ CẬP NHẬT LÊN WEB"))
