# Form implementation generated from reading ui file 'D:\NAM_1\Kythuatlaptrinh\K25411_KTLT\dang_nhap\ui\verifyOTPMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 700)
        MainWindow.setStyleSheet("background-color: #FDF0E0;")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.otpCard = QtWidgets.QFrame(parent=self.centralwidget)
        self.otpCard.setMinimumSize(QtCore.QSize(400, 450))
        self.otpCard.setMaximumSize(QtCore.QSize(400, 450))
        self.otpCard.setStyleSheet("background-color: white; border-radius: 30px;")
        self.otpCard.setObjectName("otpCard")
        self.logoLabel = QtWidgets.QLabel(parent=self.otpCard)
        self.logoLabel.setGeometry(QtCore.QRect(150, 30, 100, 100))
        self.logoLabel.setPixmap(QtGui.QPixmap("D:\\NAM_1\\Kythuatlaptrinh\\K25411_KTLT\\dang_nhap\\ui\\../images/logo.png"))
        self.logoLabel.setScaledContents(True)
        self.logoLabel.setObjectName("logoLabel")
        self.titleLabel = QtWidgets.QLabel(parent=self.otpCard)
        self.titleLabel.setGeometry(QtCore.QRect(0, 140, 400, 40))
        self.titleLabel.setStyleSheet("color: rgb(165, 54, 27); font: 700 18pt \'Segoe UI\';")
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.labelInfo = QtWidgets.QLabel(parent=self.otpCard)
        self.labelInfo.setGeometry(QtCore.QRect(40, 190, 320, 40))
        self.labelInfo.setStyleSheet("color: #666; font-size: 11px;")
        self.labelInfo.setWordWrap(True)
        self.labelInfo.setObjectName("labelInfo")
        self.lineEditOTP = QtWidgets.QLineEdit(parent=self.otpCard)
        self.lineEditOTP.setGeometry(QtCore.QRect(40, 240, 320, 50))
        self.lineEditOTP.setStyleSheet("border: 2px solid #FF9966; border-radius: 12px; padding-left: 15px; font-size: 18pt; font-weight: bold; letter-spacing: 10px;")
        self.lineEditOTP.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEditOTP.setObjectName("lineEditOTP")
        self.pushButtonVerify = QtWidgets.QPushButton(parent=self.otpCard)
        self.pushButtonVerify.setGeometry(QtCore.QRect(40, 310, 320, 50))
        self.pushButtonVerify.setStyleSheet("background-color: #FF6600; color: white; font-weight: bold; font-size: 14pt; border-radius: 15px;")
        self.pushButtonVerify.setObjectName("pushButtonVerify")
        self.pushButtonResend = QtWidgets.QPushButton(parent=self.otpCard)
        self.pushButtonResend.setGeometry(QtCore.QRect(40, 380, 320, 20))
        self.pushButtonResend.setStyleSheet("border: none; color: #777; text-decoration: underline;")
        self.pushButtonResend.setObjectName("pushButtonResend")
        self.horizontalLayout.addWidget(self.otpCard)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "New Year Photo - Xác thực OTP"))
        self.titleLabel.setText(_translate("MainWindow", "Xác thực mã OTP"))
        self.labelInfo.setText(_translate("MainWindow", "Vui lòng nhập mã xác thực gồm 6 chữ số đã được gửi đến Gmail của bạn."))
        self.lineEditOTP.setPlaceholderText(_translate("MainWindow", "------"))
        self.pushButtonVerify.setText(_translate("MainWindow", "Xác nhận mã"))
        self.pushButtonResend.setText(_translate("MainWindow", "Chưa nhận được mã? Gửi lại ngay"))
